### ISSUE TITLE
Question: SSIM difference

### ISSUE THREAD

**Issue by sinievanderben** [up42/image-similarity-measures#26]
Hi there!

I had a quick question. The skimage.metrics also has a structural similarity index measure. If I apply yours and the one of skimage to the same image, I get different results. Do you might know why this is the case?

Kind regards!

**Comment by sinievanderben** [comment]
Maybe I have to mention that I tried to adjust the parameters of skimage ssim, such as data range, sigma, K1 and K2, gaussian weight, sample covariance etc.

**Comment by markusuwe** [comment]
> Maybe I have to mention that I tried to adjust the parameters of skimage ssim, such as data range, sigma, K1 and K2, gaussian weight, sample covariance etc.

Hi. For SSIM we use the skimage implementation under the hood. See https://github.com/up42/image-similarity-measures/blob/master/image_similarity_measures/quality_metrics.py#L191 . So if there is any difference then it is caused by the parameters. As you can see in the code we set both data_range and multichannel.

**Comment by sinievanderben** [comment]
Thank you for the response! (: Is there a specific reason why max_p=4095 and therefore the datarange is 4095?

**Comment by markusuwe** [comment]
> Thank you for the response! (: Is there a specific reason why max_p=4095 and therefore the datarange is 4095?

Radiance and reflectance is usually stored in 12 bit, 2**12 is 4096, so the value range is theoretically 0..4095
